### ISSUE TITLE
This package depends on types from @mdx-js/mdx but prebundles the code and doesn't have @mdx-js/mdx as a dependency

### ISSUE THREAD

**Issue by joshwooding** [storybookjs/mdx2-csf#29]
**Describe the bug**

See https://unpkg.com/@storybook/mdx2-csf@0.1.0-next.8/dist/index.d.ts
This means that mdxCompileOptions is unknown

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by joshwooding** [comment]
yeah... I tried the naive approach by adding the package to the dts resolve option in tsup but couldn't get it to work

**Comment by ndelangen** [comment]
The real question is... why isn't it prebundling the types from that package?

**Comment by ndelangen** [comment]
Seems this was actually fixed by @joshwooding 's PR 🎉
