### ISSUE TITLE
Use mdx2-csf to support stories in mdx2 in v7

### ISSUE THREAD

**Issue by micDropper** [storybookjs/mdx2-csf#40]
**Is your feature request related to a problem? Please describe.**
We heavily used MDX1 in v6 to define and render our Vue 3 stories. V7 [seems to have deprecated this functionality](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mdx-docs-files), which means we have a lot of migration work to do now. 

**Describe the solution you'd like**
As a storybooker, I'd love to use MDX2 to define stories in storybook v7. If I can't, I'd like to minimize time spent migrating MDX1 stories to CSF, so I need better migration documentation/solutions.

**Describe alternatives you've considered**
Considered staying on v6 until we can justify the effort to rewrite our stories. 

**Additional context**
I don't really understand what mdx2-csf is for, which is why I'm creating the issue here. Adding some user-centered info to the readme would be a plus :)

**Comment by JReinhold** [comment]
Hi @micDropper!

You are still able to upgrade to v7 and MDX2, and still define your Vue3 stories in MDX. Everything should still be supported in v7 and MDX2, it's just deprecated. This means that the feature will most likely be fully removed in the next major release, but it's still part of 7.0.

Furthermore, after you've upgraded to 7.0 you can run a manual migration we've created with `npx sb@latest migrate mdx-to-csf` which will attempt to migrate all your MDX stories to CSF stories. It most likely doesn't support all edge cases but it should be a good starting point for your migration path.

**Comment by micDropper** [comment]
Thank you for the clarity!
